export const Languages = [
  // Si elige inglés
  "English",
  "Spanish",
  "Catalan",

  // Si elige español
  "Inglés",
  "Español",
  "Catalán",

  // Si elige catalán
  "Anglès",
  "Castellà",
  "Català",
];

export const cardData = [
  {
    id: "UABMèdia",
    category: {
      English: "web",
      Spanish: "web",
      Catalan: "web",
    },

    title: "UAB MÈDIA",
    pointOfInterestX: 70,
    pointOfInterestY: 110,
    textColor: "#000",
    width: 450,
    backgroundColor: "#faabff",
    path: "/UABMèdia/0.png",
    tags: ["PHP", "WebTV", "BOOTSTRAP", "JQUERY", "AWS"],
    description: [
      "Web aplication to manage the UAB Mèdia's webtv",
      "Aplicación web para la gestión de contenidos de UAB Mèdia",
      "Aplicació web per a la gestió de continguts de la UAB Mèdia",
    ],

    link: "https://uab.media/",
  },
  {
    id: "NUWE",
    category: {
      English: "design",
      Spanish: "diseño",
      Catalan: "disseny",
    },
    title: "NUWE",
    pointOfInterestX: 120,
    pointOfInterestY: 70,
    textColor: "#000",
    width: 700,
    backgroundColor: "#aaffaa",
    path: "/NUWE/0.png",
    tags: ["Figma", "Illustrator", "Photoshop"],
    description: ["aaa", "bbb", "ccc"],
    link: "https://nuwe.io/en",
  },

  {
    id: "Rispot",
    category: {
      English: "web",
      Spanish: "web",
      Catalan: "web",
    },
    title: "Rispot",
    pointOfInterestX: -50,
    pointOfInterestY: 90,
    textColor: "#000",
    width: 600,
    backgroundColor: "#abfeff",
    path: "/Rispot/0.png",
    tags: ["PHP", "SQL", "JQUERY"],
    description: ["aaa", "bbb", "ccc"],
    link:
      "https://www.amazon.es/s?i=merchant-items&me=A1O24E5ASY81J5&rh=p_4%3ARISPOT",
  },
  {
    id: "GubauAfternoons",
    category: {
      English: "web",
      Spanish: "web",
      Catalan: "web",
    },
    title: "Gubau's Afternoons",
    pointOfInterestX: 50,
    pointOfInterestY: 120,
    textColor: "#000",
    width: 470,
    backgroundColor: "#abbaff",
    path: "/GubauAfternoons/0.png",
    tags: ["HTML", "SCSS", "JQUERY"],
    description: ["aaa", "bbb", "ccc"],
    link: "https://gubauafternoons.com/",
  },
  {
    id: "Unbrushed",
    category: {
      English: "web",
      Spanish: "web",
      Catalan: "web",
    },
    title: "Unbrushed",
    pointOfInterestX: 0,
    pointOfInterestY: 0,
    textColor: "#000",
    width: 700,
    backgroundColor: "#ffabd5",
    path: "/Unbrushed/0.png",
    tags: ["PHP", "SQL", "JavaScript"],
    description: ["aaa", "bbb", "ccc"],
    link: "https://pol-uab.alwaysdata.net/Otros/Unbrushed_PHP/Code/",
  },
  {
    id: "Skatla",
    category: {
      English: "design",
      Spanish: "diseño",
      Catalan: "disseny",
    },
    title: "Skatla",
    pointOfInterestX: 60,
    pointOfInterestY: 80,
    textColor: "#000000",
    width: 400,
    backgroundColor: "#ffdbab",
    path: "/Skatla/0.png",
    tags: ["Indesign", "Illustrator", "Photoshop"],
    description: ["aaa", "bbb", "ccc"],
    link: "https://www.instagram.com/skatlapack/",
  },
  {
    id: "ThoseColors",
    category: {
      English: "web",
      Spanish: "web",
      Catalan: "web",
    },
    title: "Those Colors",
    pointOfInterestX: 40,
    pointOfInterestY: 70,
    textColor: "#000000",
    width: 500,
    backgroundColor: "#feffab",
    path: "/ThoseColors/0.png",
    tags: ["PHP", "SASS"],
    description: ["aaa", "bbb", "ccc"],
    link: "https://pol-uab.alwaysdata.net/Otros/ThoseColors/index.php",
  },
  {
    id: "Memo",
    category: {
      English: "web",
      Spanish: "web",
      Catalan: "web",
    },
    title: "Memo",
    pointOfInterestX: 40,
    pointOfInterestY: 120,
    textColor: "#000000",
    width: 600,
    backgroundColor: "#e6abff",
    path: "/Memo/0.png",
    tags: ["Javascript", "HTML", "CSS"],
    description: ["aaa", "bbb", "ccc"],
    link: "https://pol-uab.alwaysdata.net/Otros/memo/",
  },
];
