import {
  TbBrandAdobe,
  TbBrandAngular,
  TbBrandBootstrap,
  TbBrandFigma,
  TbBrandGatsby,
  TbBrandJavascript,
  TbBrandNextjs,
  TbBrandReact,
  TbBrandRedux,
  TbBrandSketch,
  TbBrandTypescript,
  TbBrandVue,
} from "react-icons/tb";
import { SiMaterialdesign } from "react-icons/si";
import {
  WhatIsAdobeXd,
  WhatIsAngular,
  WhatIsBootstrap,
  WhatIsMaterialDesign,
  WhatIsNext,
  WhatIsReactContent,
  WhatIsReduxContent,
  WhatIsSketch,
  WhatIsTypescript,
  WhatIsVue,
  WhatIsFigma,
  WhatIsGatsby,
} from "./Texts";
import { JS_BeginnersGuide } from "./Texts/JS_BeginnersGuide";

export interface IBlogData {
  id: string;
  name: string;
  path: string;
  icon: React.ReactNode;
  color: string;
  tags: string[];
  content: string;
  author: string;
  level: string;
  date: string;
}

const courseData: IBlogData[] = [
  {
    id: "course-0",
    name: "What is React?",
    path: "WhatIsReact",
    tags: ["React", "JavaScript", "Frontend"],
    icon: <TbBrandReact />,
    color: "#61dafb",
    content: WhatIsReactContent,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-05-03",
  },

  {
    id: "course-1",
    name: "What is Redux?",
    path: "what-is-redux",
    tags: ["Redux", "JavaScript", "Frontend"],
    icon: <TbBrandRedux />,
    color: "#764abc",
    content: WhatIsReduxContent,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-2",
    name: "What is TypeScript?",
    path: "what-is-typescript",
    tags: ["TypeScript", "JavaScript", "Frontend"],
    icon: <TbBrandTypescript />,
    color: "#007acc",
    content: WhatIsTypescript,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-9",
    name: "What is Figma?",
    path: "what-is-figma",
    tags: ["Figma", "Design", "UI"],
    icon: <TbBrandFigma />,
    color: "#f24e1e",
    content: WhatIsFigma,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-18-03",
  },
  {
    id: "course-11",
    name: "What is Next.js?",
    path: "what-is-nextjs",
    tags: ["Server-Rendered", "React", "Frontend"],
    icon: <TbBrandNextjs />,
    color: "#000000",
    content: WhatIsNext,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-18-03",
  },
  {
    id: "course-6",
    name: "What is Material Design?",
    path: "what-is-material-design",
    tags: ["Material Design", "UI", "Interface"],
    icon: <SiMaterialdesign />,
    color: "#0081cb",
    content: WhatIsMaterialDesign,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-12",
    name: "JavaScript: A Beginner's Guide",
    path: "what-is-js",
    tags: ["Javascript", "Website", "Frontend"],
    icon: <TbBrandJavascript />,
    color: "#f7df1e",
    content: JS_BeginnersGuide,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-19-03",
  },
  {
    id: "course-3",
    name: "What is Vue?",
    path: "what-is-vue",
    tags: ["Vue", "JavaScript", "Frontend"],
    icon: <TbBrandVue />,
    color: "#41b883",
    content: WhatIsVue,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-4",
    name: "What is Angular?",
    path: "what-is-angular",
    tags: ["Angular", "JavaScript", "Frontend"],
    icon: <TbBrandAngular />,
    color: "#dd1b16",
    content: WhatIsAngular,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-5",
    name: "What is Bootstrap?",
    path: "what-is-bootstrap",
    tags: ["Bootstrap", "CSS", "UI"],
    icon: <TbBrandBootstrap />,
    color: "#563d7c",
    content: WhatIsBootstrap,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-7",
    name: "What is Adobe XD?",
    path: "what-is-adobe-xd",
    tags: ["UI", "Design", "Prototype"],
    icon: <TbBrandAdobe />,
    color: "#ff61f6",
    content: WhatIsAdobeXd,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-8",
    name: "What is Sketch?",
    path: "what-is-sketch",
    tags: ["Sketch", "Design", "UI"],
    icon: <TbBrandSketch />,
    color: "#ff9a00",
    content: WhatIsSketch,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-16-03",
  },
  {
    id: "course-10",
    name: "What is Gatsby?",
    path: "what-is-gatsby",
    tags: ["Gatsby", "React", "Frontend"],
    icon: <TbBrandGatsby />,
    color: "#663399",
    content: WhatIsGatsby,
    author: "Pol Gubau Amores",
    level: "Beginner",
    date: "2023-18-03",
  },
];

export default courseData;
