import { BiUserCircle, BiWorld } from "react-icons/bi";
import { CgPerformance } from "react-icons/cg";
import { FaRegIdCard } from "react-icons/fa";
import {
  MdAlternateEmail,
  MdClose,
  MdOutlineNotListedLocation,
  MdOutlineShortcut,
  MdOutlineTextsms,
  MdSave,
} from "react-icons/md";
import {
  RiMedalFill,
  RiMenuUnfoldLine,
  RiPoliceCarFill,
  RiShieldUserLine,
} from "react-icons/ri";
import {
  TbAdjustmentsAlt,
  TbAlarm,
  TbAlertTriangle,
  TbMenu2,
  TbPlus,
  TbTrash,
  TbBinaryTree2,
  TbBinaryTree,
  TbBinary,
  TbBook,
  TbBookmark,
  TbBraces,
  TbBrackets,
  TbBulb,
  TbCalendar,
  TbCamera,
  TbCheck,
  TbAsset,
  TbBrandCitymapper,
  TbColorSwatch,
  TbForms,
  TbScriptPlus,
  TbArrowDown,
  TbArrowLeft,
  TbArrowRight,
  TbArrowUp,
  TbAugmentedReality2,
  TbBarcode,
  TbClipboard,
  TbClockHour4,
  TbCode,
  TbCurrencyEuro,
  TbCurrencyDollar,
  TbCurrencyYen,
  TbLocation,
  TbBuilding,
  TbCurrentLocation,
  TbBuildingStore,
  TbApps,
  TbTransform,
  TbDevices2,
  TbMoodCrazyHappy,
  TbPageBreak,
  TbRoute,
  TbRouter,
  TbDeviceIpad,
  TbTemplate,
  TbFileText,
  TbServerBolt,
  TbWifi,
  TbHeart,
  TbStar,
  TbBuildingCastle,
  TbMessages,
  TbDatabase,
  TbBuildingCommunity,
  TbHome,
  TbUpload,
  TbCloudUpload,
  TbLink,
  TbQuestionMark,
  TbEdit,
} from "react-icons/tb";
import { TiFlowSwitch } from "react-icons/ti";

export const icons = [
  { id: "0", name: "plus", icon: <TbPlus /> },
  { id: "4", name: "menus", icon: <TbMenu2 /> },
  { id: "5", name: "alarm", icon: <TbAlarm /> },
  { id: "6", name: "TbTrash", icon: <TbTrash /> },
  { id: "7", name: "warning", icon: <TbAlertTriangle /> },
  { id: "8", name: "settings", icon: <TbAdjustmentsAlt /> },
  { id: "9", name: "binnaryTree", icon: <TbBinaryTree2 /> },
  { id: "10", name: "bigBinnaryTree", icon: <TbBinaryTree /> },
  { id: "11", name: "binary", icon: <TbBinary /> },
  { id: "12", name: "book", icon: <TbBook /> },
  { id: "13", name: "bookmark", icon: <TbBookmark /> },
  { id: "14", name: "braces", icon: <TbBraces /> },
  { id: "15", name: "brackets", icon: <TbBrackets /> },
  { id: "16", name: "light", icon: <TbBulb /> },
  { id: "17", name: "calendar", icon: <TbCalendar /> },
  { id: "18", name: "camera", icon: <TbCamera /> },
  { id: "19", name: "check", icon: <TbCheck /> },
  { id: "20", name: "asset", icon: <TbAsset /> },
  { id: "21", name: "map", icon: <TbBrandCitymapper /> },
  { id: "22", name: "form", icon: <TbForms /> },
  { id: "23", name: "script", icon: <TbScriptPlus /> },
  { id: "24", name: "palette", icon: <TbColorSwatch /> },
  { id: "25", name: "user", icon: <BiUserCircle /> },
  { id: "26", name: "user", icon: <BiUserCircle /> },
  { id: "27", name: "ar", icon: <TbAugmentedReality2 /> },
  { id: "28", name: "world", icon: <BiWorld /> },
  { id: "29", name: "idcard", icon: <FaRegIdCard /> },
  { id: "30", name: "medal", icon: <RiMedalFill /> },
  { id: "31", name: "policecar", icon: <RiPoliceCarFill /> },
  { id: "32", name: "arrowright", icon: <TbArrowRight /> },
  { id: "33", name: "arrow", icon: <TbArrowRight /> },
  { id: "34", name: "arrowleft", icon: <TbArrowLeft /> },
  { id: "35", name: "arrowup", icon: <TbArrowUp /> },
  { id: "36", name: "arrowdown", icon: <TbArrowDown /> },
  { id: "37", name: "scan", icon: <TbBarcode /> },
  { id: "38", name: "object", icon: <TbBraces /> },
  { id: "39", name: "array", icon: <TbBrackets /> },
  { id: "40", name: "check", icon: <TbCheck /> },
  { id: "41", name: "paste", icon: <TbClipboard /> },
  { id: "42", name: "clock", icon: <TbClockHour4 /> },
  { id: "43", name: "code", icon: <TbCode /> },
  { id: "44", name: "euro", icon: <TbCurrencyEuro /> },
  { id: "45", name: "dollar", icon: <TbCurrencyDollar /> },
  { id: "46", name: "yen", icon: <TbCurrencyYen /> },
  { id: "47", name: "forms", icon: <TbForms /> },
  { id: "49", name: "profile", icon: <RiShieldUserLine /> },
  { id: "50", name: "location", icon: <TbLocation /> },
  { id: "51", name: "department", icon: <TbBuilding /> },
  { id: "52", name: "position", icon: <TbCurrentLocation /> },
  { id: "83", name: "pointer", icon: <MdOutlineNotListedLocation /> },
  { id: "84", name: "store", icon: <TbBuildingStore /> },
  { id: "85", name: "menuRigth", icon: <RiMenuUnfoldLine /> },
  { id: "53", name: "apps", icon: <TbApps /> },
  { id: "54", name: "performance", icon: <CgPerformance /> },
  { id: "55", name: "transform", icon: <TbTransform /> },
  { id: "56", name: "device", icon: <TbDevices2 /> },
  { id: "56", name: "crazyHappy", icon: <TbMoodCrazyHappy /> },
  { id: "57", name: "pageBreak", icon: <TbPageBreak /> },
  { id: "58", name: "wizard", icon: <TbRoute /> },
  { id: "59", name: "router", icon: <TbRouter /> },
  { id: "60", name: "ipad", icon: <TbDeviceIpad /> },
  { id: "61", name: "flowSwitch", icon: <TiFlowSwitch /> },
  { id: "62", name: "sms", icon: <MdOutlineTextsms /> },
  { id: "63", name: "email", icon: <MdAlternateEmail /> },
  { id: "64", name: "template", icon: <TbTemplate /> },
  { id: "64", name: "file", icon: <TbFileText /> },
  { id: "64", name: "server", icon: <TbServerBolt /> },
  { id: "65", name: "Global Forms", icon: <TbForms /> },
  { id: "65", name: "Global Object Definitions", icon: <TbBraces /> },
  { id: "66", name: "TI Connectors", icon: <TbDevices2 /> },
  { id: "67", name: "shortcut", icon: <MdOutlineShortcut /> },
  { id: "68", name: "wifi", icon: <TbWifi /> },
  { id: "69", name: "hearth", icon: <TbHeart /> },
  { id: "70", name: "star", icon: <TbStar /> },
  { id: "71", name: "castle", icon: <TbBuildingCastle /> },
  { id: "72", name: "messages", icon: <TbMessages /> },
  { id: "73", name: "database", icon: <TbDatabase /> },
  { id: "74", name: "scripts", icon: <TbScriptPlus /> },
  { id: "75", name: "departments", icon: <TbBuildingCommunity /> },
  { id: "76", name: "home", icon: <TbHome /> },
  { id: "77", name: "globalCodeSystems", icon: <TbCode /> },
  { id: "78", name: "tenantCodeSystems", icon: <TbCode /> },
  { id: "79", name: "terminals", icon: <TbDeviceIpad /> },
  { id: "80", name: "globalwizardflows", icon: <TbRoute /> },
  { id: "81", name: "tenantwizardflows", icon: <TiFlowSwitch /> },
  { id: "82", name: "globalforms", icon: <TbForms /> },
  { id: "86", name: "wizardsteptypes", icon: <TbRouter /> },
  { id: "87", name: "smsprovidersettings", icon: <TbServerBolt /> },
  { id: "88", name: "smstemplate", icon: <MdOutlineTextsms /> },
  { id: "89", name: "emailsmtpsettings", icon: <MdAlternateEmail /> },
  { id: "90", name: "emailtemplate", icon: <TbTemplate /> },
  { id: "91", name: "ticonnectors", icon: <TbDevices2 /> },
  { id: "92", name: "upload", icon: <TbUpload /> },
  { id: "93", name: "uploadCloud", icon: <TbCloudUpload /> },
  { id: "94", name: "close", icon: <MdClose /> },
  { id: "94", name: "trash", icon: <TbTrash /> },
  { id: "95", name: "save", icon: <MdSave /> },
  { id: "96", name: "link", icon: <TbLink /> },
  { id: "97", name: "question", icon: <TbQuestionMark /> },
  { id: "98", name: "edit", icon: <TbEdit /> },
];

type Icon = (typeof icons)[number];

type IconNames = Icon["name"];

export default icons;
export type { Icon, IconNames };
