export const tagsDatabase = [
  "db",
  "bd",
  "ddbb",
  "bbdd",
  "databases",
  "sql",
  "nosql",
  "mongodb",
  "mysql",
  "postgresql",
  "postgres",
  "oracle",
  "mariadb",
  "CRUD",
  "create",
  "read",
  "update",
  "delete",
  "base de datos",
  "dades",
  "datos",
  "data",
  "bigData",
  "big data",
  "science",
  "scientist",
  "analysis",
  "analyst",
  "engineer",
  "visualization",
  "vizualization",
  "vizualisation",
  "vizualiser",
];
export const tagsMobile = [
  "mobile",
  "responsive",
  "all devices",
  "devices",
  "responsive design",
  "responsive web design",
  "responsive websites",
  "responsive websites",
  "responsive web sites",
  "responsive web pages",
];
export const tagsLogin = [
  "users",
  "login",
  "database",
  "crud",
  "signup",
  "signin",
];
export const tagsJS = ["js", "javascript", "moderno", ".js", "ecma", "es6"];
export const tagsDesign = [
  "design",
  "figma",
  "ux",
  "ui",
  "feminism",
  "modern",
  "developer",
  "adobe",
  "photoshop",
  "illustrator",
  "diseño",
  "diseñadora",
  "diseño web",
  "diseño gráfico",
  "diseño de producto",
  "diseño de interacción",
  "diseño de experiencia",
  "diseño de servicios",
  "interface",
  "interfaz",
  "rollup",
  "roll up",
  "roll-up",
  "diseño de productos",
  "diseño de servicios",
];
